### ISSUE TITLE
1.0.16 npm build seems to be corrupted

### ISSUE THREAD

**Issue by modosc** [binarykitchen/spider-detector#7]
i can successfully install `1.0.15` with both `npm` and `yarn` but not `1.0.16`:
```
yarn add v0.22.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/spider-detector/-/spider-detector-1.0.16.tgz: invalid tar file".
info If you think this is a bug, please open a bug report with the information provided in "/Users/jon/git/instaflux/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Trace:
  Error: https://registry.yarnpkg.com/spider-detector/-/spider-detector-1.0.16.tgz: invalid tar file
      at Extract.Parse._startEntry (/Users/jon/.nvm/versions/node/v6.9.5/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/Users/jon/.nvm/versions/node/v6.9.5/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/Users/jon/.nvm/versions/node/v6.9.5/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:188:7)
      at BlockStream._emitChunk (/Users/jon/.nvm/versions/node/v6.9.5/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.flush (/Users/jon/.nvm/versions/node/v6.9.5/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:70:8)
      at BlockStream.end (/Users/jon/.nvm/versions/node/v6.9.5/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:66:8)
      at Extract.Parse.end (/Users/jon/.nvm/versions/node/v6.9.5/lib/node_modules/yarn/node_modules/tar/lib/parse.js:86:23)
      at UnpackStream.onend (_stream_readable.js:511:10)
```
```
laptop ~/git npm install spider-detector@1.0.16
npm ERR! cb() never called!
```

**Comment by binarykitchen** [comment]
@modosc had a look and can reproduce that too. but the tar file `https://registry.yarnpkg.com/spider-detector/-/spider-detector-1.0.16.tgz` seems to be valid and is not corrupted. think i ll report this to yarn ...

**Comment by 26medias** [comment]
Same issue here, no way to `npm install`:

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julie\AppData\Roaming\npm-cache\_logs\2017-04-20T18_24_20_258Z-debug.log
```

**Log file:**
https://pastebin.com/apPKhe0h

**Comment by 26medias** [comment]
Same issue here, no way to `npm install`:

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\julie\AppData\Roaming\npm-cache\_logs\2017-04-20T18_24_20_258Z-debug.log
```

**Log file:**
https://pastebin.com/apPKhe0h

**Comment by binarykitchen** [comment]
okay guys, i think there was a glitch when i published last time. network or npm. have bumped to a new version, published it and tested successfully.
